---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "aggregatedata-details"
  namespace: "default"
  labels:
    app: "aggregatedata-details"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "aggregatedata-details"
  template:
    metadata:
      labels:
        app: "aggregatedata-details"
    spec:
      containers:
      - name: "aggregatedetails-1"
        image: "gcr.io/microapp-280010/aggregatedetails:v5"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "aggregatedata-details-hpa-nwew"
  namespace: "default"
  labels:
    app: "aggregatedata-details"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "aggregatedata-details"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
