---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "aggregatedata-details-service"
  namespace: "default"
  labels:
    app: "aggregatedata-details"
spec:
  ports:
  - protocol: "TCP"
    port: 8080
  selector:
    app: "aggregatedata-details"
  type: "LoadBalancer"
  loadBalancerIP: ""
