apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-12T19:14:34Z"
  name: mysql-service
  namespace: default
  resourceVersion: "414241"
  selfLink: /api/v1/namespaces/default/services/mysql-service
  uid: f35ef9c2-ace0-11ea-a058-42010a800258
spec:
  clusterIP: 10.8.3.151
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31645
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 104.198.70.141
