apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"mysql-pv-claim","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"20Gi"}}}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: "2020-06-13T11:34:25Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: mysql-pv-claim
  namespace: default
  resourceVersion: "625933"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/mysql-pv-claim
  uid: d5791caf-ad69-11ea-a058-42010a800258
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-d5791caf-ad69-11ea-a058-42010a800258
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  phase: Bound