---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "user-details-service"
  namespace: "default"
  labels:
    app: "user-details"
spec:
  ports:
  - protocol: "TCP"
    port: 8080
  selector:
    app: "user-details"
  type: "ClusterIP"
